# Generated by Django 2.2.16 on 2022-10-11 11:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221011_1116'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_self_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, following=django.db.models.expressions.F('user')), name='self_following_is_not_allowed'),
        ),
    ]
